/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as PanelRouteImport } from './routes/_panel'
import { Route as R404RouteImport } from './routes/404'
import { Route as R403RouteImport } from './routes/403'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResetPasswordKeyRouteImport } from './routes/reset-password.$key'
import { Route as RegisterVerifyPhoneRouteImport } from './routes/register.verify-phone'
import { Route as RegisterStatusRouteImport } from './routes/register.status'
import { Route as PanelWalletRouteImport } from './routes/_panel.wallet'
import { Route as PanelUsersRouteImport } from './routes/_panel.users'
import { Route as PanelTagsRouteImport } from './routes/_panel.tags'
import { Route as PanelSupportRouteImport } from './routes/_panel.support'
import { Route as PanelSubscribersRouteImport } from './routes/_panel.subscribers'
import { Route as PanelStoresRouteImport } from './routes/_panel.stores'
import { Route as PanelReturnsRouteImport } from './routes/_panel.returns'
import { Route as PanelPropertyValuesRouteImport } from './routes/_panel.property-values'
import { Route as PanelPropertiesRouteImport } from './routes/_panel.properties'
import { Route as PanelProductsRouteImport } from './routes/_panel.products'
import { Route as PanelPaymentMethodsRouteImport } from './routes/_panel.payment-methods'
import { Route as PanelOrdersRouteImport } from './routes/_panel.orders'
import { Route as PanelNotificationsRouteImport } from './routes/_panel.notifications'
import { Route as PanelInvoicesRouteImport } from './routes/_panel.invoices'
import { Route as PanelDashboardRouteImport } from './routes/_panel.dashboard'
import { Route as PanelCustomersRouteImport } from './routes/_panel.customers'
import { Route as PanelCouriersRouteImport } from './routes/_panel.couriers'
import { Route as PanelCouponsRouteImport } from './routes/_panel.coupons'
import { Route as PanelCollectionsRouteImport } from './routes/_panel.collections'
import { Route as PanelChatRouteImport } from './routes/_panel.chat'
import { Route as PanelCategoriesRouteImport } from './routes/_panel.categories'
import { Route as PanelAssetsRouteImport } from './routes/_panel.assets'
import { Route as PanelAccountRouteImport } from './routes/_panel.account'
import { Route as PanelSplatRouteImport } from './routes/_panel.$'
import { Route as PanelUsersNewRouteImport } from './routes/_panel.users.new'
import { Route as PanelUsersIdRouteImport } from './routes/_panel.users.$id'
import { Route as PanelSupportSessionIdRouteImport } from './routes/_panel.support.$sessionId'
import { Route as PanelStoresIdRouteImport } from './routes/_panel.stores.$id'
import { Route as PanelReviewsStoreRouteImport } from './routes/_panel.reviews.store'
import { Route as PanelReviewsProductRouteImport } from './routes/_panel.reviews.product'
import { Route as PanelReturnsIdRouteImport } from './routes/_panel.returns.$id'
import { Route as PanelProductsNewRouteImport } from './routes/_panel.products.new'
import { Route as PanelPaymentMethodsNewRouteImport } from './routes/_panel.payment-methods.new'
import { Route as PanelOrdersIdRouteImport } from './routes/_panel.orders.$id'
import { Route as PanelInvoicesIdRouteImport } from './routes/_panel.invoices.$id'
import { Route as PanelHelpTermsRouteImport } from './routes/_panel.help.terms'
import { Route as PanelHelpPrivacyRouteImport } from './routes/_panel.help.privacy'
import { Route as PanelHelpFaqRouteImport } from './routes/_panel.help.faq'
import { Route as PanelHelpArticlesRouteImport } from './routes/_panel.help.articles'
import { Route as PanelCustomersIdRouteImport } from './routes/_panel.customers.$id'
import { Route as PanelCouponsNewRouteImport } from './routes/_panel.coupons.new'
import { Route as PanelCommunicationsTemplatesRouteImport } from './routes/_panel.communications.templates'
import { Route as PanelCommunicationsChannelsRouteImport } from './routes/_panel.communications.channels'
import { Route as PanelCollectionsNewRouteImport } from './routes/_panel.collections.new'
import { Route as PanelChatUserIdRouteImport } from './routes/_panel.chat.$userId'
import { Route as PanelAdminVisitorsRouteImport } from './routes/_panel.admin.visitors'
import { Route as PanelAdminUserPoliciesRouteImport } from './routes/_panel.admin.user-policies'
import { Route as PanelAdminSearchHistoryRouteImport } from './routes/_panel.admin.search-history'
import { Route as PanelAdminRolesRouteImport } from './routes/_panel.admin.roles'
import { Route as PanelAdminRolePoliciesRouteImport } from './routes/_panel.admin.role-policies'
import { Route as PanelAdminPermissionsRouteImport } from './routes/_panel.admin.permissions'
import { Route as PanelAdminPermissionResourcesRouteImport } from './routes/_panel.admin.permission-resources'
import { Route as PanelAdminOptionsRouteImport } from './routes/_panel.admin.options'
import { Route as PanelAdminFeedbackRouteImport } from './routes/_panel.admin.feedback'
import { Route as PanelAdminAuditLogRouteImport } from './routes/_panel.admin.audit-log'
import { Route as PanelAccountSessionsRouteImport } from './routes/_panel.account.sessions'
import { Route as PanelAccountPreferencesRouteImport } from './routes/_panel.account.preferences'
import { Route as PanelAccountNotificationsPrefsRouteImport } from './routes/_panel.account.notifications-prefs'
import { Route as PanelAccountDevicesRouteImport } from './routes/_panel.account.devices'
import { Route as PanelAccountChangePasswordRouteImport } from './routes/_panel.account.change-password'
import { Route as PanelProductsIdReviewsRouteImport } from './routes/_panel.products.$id.reviews'
import { Route as PanelProductsIdEditRouteImport } from './routes/_panel.products.$id.edit'
import { Route as PanelPaymentMethodsIdEditRouteImport } from './routes/_panel.payment-methods.$id.edit'
import { Route as PanelHelpFaqNewRouteImport } from './routes/_panel.help.faq.new'
import { Route as PanelCouriersIdEditRouteImport } from './routes/_panel.couriers.$id.edit'
import { Route as PanelCouponsIdRedemptionsRouteImport } from './routes/_panel.coupons.$id.redemptions'
import { Route as PanelCouponsIdEditRouteImport } from './routes/_panel.coupons.$id.edit'
import { Route as PanelCollectionsIdEditRouteImport } from './routes/_panel.collections.$id.edit'
import { Route as PanelAdminLocationsRegionsRouteImport } from './routes/_panel.admin.locations.regions'
import { Route as PanelAdminLocationsLanguagesRouteImport } from './routes/_panel.admin.locations.languages'
import { Route as PanelAdminLocationsCurrenciesRouteImport } from './routes/_panel.admin.locations.currencies'
import { Route as PanelAdminLocationsCountriesRouteImport } from './routes/_panel.admin.locations.countries'
import { Route as PanelAdminLocationsCitiesRouteImport } from './routes/_panel.admin.locations.cities'
import { Route as PanelHelpFaqIdEditRouteImport } from './routes/_panel.help.faq.$id.edit'
import { Route as PanelAdminRolesIdEditRouteImport } from './routes/_panel.admin.roles.$id.edit'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelRoute = PanelRouteImport.update({
  id: '/_panel',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const R403Route = R403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordKeyRoute = ResetPasswordKeyRouteImport.update({
  id: '/reset-password/$key',
  path: '/reset-password/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterVerifyPhoneRoute = RegisterVerifyPhoneRouteImport.update({
  id: '/verify-phone',
  path: '/verify-phone',
  getParentRoute: () => RegisterRoute,
} as any)
const RegisterStatusRoute = RegisterStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => RegisterRoute,
} as any)
const PanelWalletRoute = PanelWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => PanelRoute,
} as any)
const PanelUsersRoute = PanelUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => PanelRoute,
} as any)
const PanelTagsRoute = PanelTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => PanelRoute,
} as any)
const PanelSupportRoute = PanelSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => PanelRoute,
} as any)
const PanelSubscribersRoute = PanelSubscribersRouteImport.update({
  id: '/subscribers',
  path: '/subscribers',
  getParentRoute: () => PanelRoute,
} as any)
const PanelStoresRoute = PanelStoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => PanelRoute,
} as any)
const PanelReturnsRoute = PanelReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => PanelRoute,
} as any)
const PanelPropertyValuesRoute = PanelPropertyValuesRouteImport.update({
  id: '/property-values',
  path: '/property-values',
  getParentRoute: () => PanelRoute,
} as any)
const PanelPropertiesRoute = PanelPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => PanelRoute,
} as any)
const PanelProductsRoute = PanelProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => PanelRoute,
} as any)
const PanelPaymentMethodsRoute = PanelPaymentMethodsRouteImport.update({
  id: '/payment-methods',
  path: '/payment-methods',
  getParentRoute: () => PanelRoute,
} as any)
const PanelOrdersRoute = PanelOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => PanelRoute,
} as any)
const PanelNotificationsRoute = PanelNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => PanelRoute,
} as any)
const PanelInvoicesRoute = PanelInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => PanelRoute,
} as any)
const PanelDashboardRoute = PanelDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PanelRoute,
} as any)
const PanelCustomersRoute = PanelCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => PanelRoute,
} as any)
const PanelCouriersRoute = PanelCouriersRouteImport.update({
  id: '/couriers',
  path: '/couriers',
  getParentRoute: () => PanelRoute,
} as any)
const PanelCouponsRoute = PanelCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => PanelRoute,
} as any)
const PanelCollectionsRoute = PanelCollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => PanelRoute,
} as any)
const PanelChatRoute = PanelChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => PanelRoute,
} as any)
const PanelCategoriesRoute = PanelCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => PanelRoute,
} as any)
const PanelAssetsRoute = PanelAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => PanelRoute,
} as any)
const PanelAccountRoute = PanelAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => PanelRoute,
} as any)
const PanelSplatRoute = PanelSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => PanelRoute,
} as any)
const PanelUsersNewRoute = PanelUsersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PanelUsersRoute,
} as any)
const PanelUsersIdRoute = PanelUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PanelUsersRoute,
} as any)
const PanelSupportSessionIdRoute = PanelSupportSessionIdRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => PanelSupportRoute,
} as any)
const PanelStoresIdRoute = PanelStoresIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PanelStoresRoute,
} as any)
const PanelReviewsStoreRoute = PanelReviewsStoreRouteImport.update({
  id: '/reviews/store',
  path: '/reviews/store',
  getParentRoute: () => PanelRoute,
} as any)
const PanelReviewsProductRoute = PanelReviewsProductRouteImport.update({
  id: '/reviews/product',
  path: '/reviews/product',
  getParentRoute: () => PanelRoute,
} as any)
const PanelReturnsIdRoute = PanelReturnsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PanelReturnsRoute,
} as any)
const PanelProductsNewRoute = PanelProductsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PanelProductsRoute,
} as any)
const PanelPaymentMethodsNewRoute = PanelPaymentMethodsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PanelPaymentMethodsRoute,
} as any)
const PanelOrdersIdRoute = PanelOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PanelOrdersRoute,
} as any)
const PanelInvoicesIdRoute = PanelInvoicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PanelInvoicesRoute,
} as any)
const PanelHelpTermsRoute = PanelHelpTermsRouteImport.update({
  id: '/help/terms',
  path: '/help/terms',
  getParentRoute: () => PanelRoute,
} as any)
const PanelHelpPrivacyRoute = PanelHelpPrivacyRouteImport.update({
  id: '/help/privacy',
  path: '/help/privacy',
  getParentRoute: () => PanelRoute,
} as any)
const PanelHelpFaqRoute = PanelHelpFaqRouteImport.update({
  id: '/help/faq',
  path: '/help/faq',
  getParentRoute: () => PanelRoute,
} as any)
const PanelHelpArticlesRoute = PanelHelpArticlesRouteImport.update({
  id: '/help/articles',
  path: '/help/articles',
  getParentRoute: () => PanelRoute,
} as any)
const PanelCustomersIdRoute = PanelCustomersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PanelCustomersRoute,
} as any)
const PanelCouponsNewRoute = PanelCouponsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PanelCouponsRoute,
} as any)
const PanelCommunicationsTemplatesRoute =
  PanelCommunicationsTemplatesRouteImport.update({
    id: '/communications/templates',
    path: '/communications/templates',
    getParentRoute: () => PanelRoute,
  } as any)
const PanelCommunicationsChannelsRoute =
  PanelCommunicationsChannelsRouteImport.update({
    id: '/communications/channels',
    path: '/communications/channels',
    getParentRoute: () => PanelRoute,
  } as any)
const PanelCollectionsNewRoute = PanelCollectionsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PanelCollectionsRoute,
} as any)
const PanelChatUserIdRoute = PanelChatUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => PanelChatRoute,
} as any)
const PanelAdminVisitorsRoute = PanelAdminVisitorsRouteImport.update({
  id: '/admin/visitors',
  path: '/admin/visitors',
  getParentRoute: () => PanelRoute,
} as any)
const PanelAdminUserPoliciesRoute = PanelAdminUserPoliciesRouteImport.update({
  id: '/admin/user-policies',
  path: '/admin/user-policies',
  getParentRoute: () => PanelRoute,
} as any)
const PanelAdminSearchHistoryRoute = PanelAdminSearchHistoryRouteImport.update({
  id: '/admin/search-history',
  path: '/admin/search-history',
  getParentRoute: () => PanelRoute,
} as any)
const PanelAdminRolesRoute = PanelAdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => PanelRoute,
} as any)
const PanelAdminRolePoliciesRoute = PanelAdminRolePoliciesRouteImport.update({
  id: '/admin/role-policies',
  path: '/admin/role-policies',
  getParentRoute: () => PanelRoute,
} as any)
const PanelAdminPermissionsRoute = PanelAdminPermissionsRouteImport.update({
  id: '/admin/permissions',
  path: '/admin/permissions',
  getParentRoute: () => PanelRoute,
} as any)
const PanelAdminPermissionResourcesRoute =
  PanelAdminPermissionResourcesRouteImport.update({
    id: '/admin/permission-resources',
    path: '/admin/permission-resources',
    getParentRoute: () => PanelRoute,
  } as any)
const PanelAdminOptionsRoute = PanelAdminOptionsRouteImport.update({
  id: '/admin/options',
  path: '/admin/options',
  getParentRoute: () => PanelRoute,
} as any)
const PanelAdminFeedbackRoute = PanelAdminFeedbackRouteImport.update({
  id: '/admin/feedback',
  path: '/admin/feedback',
  getParentRoute: () => PanelRoute,
} as any)
const PanelAdminAuditLogRoute = PanelAdminAuditLogRouteImport.update({
  id: '/admin/audit-log',
  path: '/admin/audit-log',
  getParentRoute: () => PanelRoute,
} as any)
const PanelAccountSessionsRoute = PanelAccountSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => PanelAccountRoute,
} as any)
const PanelAccountPreferencesRoute = PanelAccountPreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => PanelAccountRoute,
} as any)
const PanelAccountNotificationsPrefsRoute =
  PanelAccountNotificationsPrefsRouteImport.update({
    id: '/notifications-prefs',
    path: '/notifications-prefs',
    getParentRoute: () => PanelAccountRoute,
  } as any)
const PanelAccountDevicesRoute = PanelAccountDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => PanelAccountRoute,
} as any)
const PanelAccountChangePasswordRoute =
  PanelAccountChangePasswordRouteImport.update({
    id: '/change-password',
    path: '/change-password',
    getParentRoute: () => PanelAccountRoute,
  } as any)
const PanelProductsIdReviewsRoute = PanelProductsIdReviewsRouteImport.update({
  id: '/$id/reviews',
  path: '/$id/reviews',
  getParentRoute: () => PanelProductsRoute,
} as any)
const PanelProductsIdEditRoute = PanelProductsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => PanelProductsRoute,
} as any)
const PanelPaymentMethodsIdEditRoute =
  PanelPaymentMethodsIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => PanelPaymentMethodsRoute,
  } as any)
const PanelHelpFaqNewRoute = PanelHelpFaqNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PanelHelpFaqRoute,
} as any)
const PanelCouriersIdEditRoute = PanelCouriersIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => PanelCouriersRoute,
} as any)
const PanelCouponsIdRedemptionsRoute =
  PanelCouponsIdRedemptionsRouteImport.update({
    id: '/$id/redemptions',
    path: '/$id/redemptions',
    getParentRoute: () => PanelCouponsRoute,
  } as any)
const PanelCouponsIdEditRoute = PanelCouponsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => PanelCouponsRoute,
} as any)
const PanelCollectionsIdEditRoute = PanelCollectionsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => PanelCollectionsRoute,
} as any)
const PanelAdminLocationsRegionsRoute =
  PanelAdminLocationsRegionsRouteImport.update({
    id: '/admin/locations/regions',
    path: '/admin/locations/regions',
    getParentRoute: () => PanelRoute,
  } as any)
const PanelAdminLocationsLanguagesRoute =
  PanelAdminLocationsLanguagesRouteImport.update({
    id: '/admin/locations/languages',
    path: '/admin/locations/languages',
    getParentRoute: () => PanelRoute,
  } as any)
const PanelAdminLocationsCurrenciesRoute =
  PanelAdminLocationsCurrenciesRouteImport.update({
    id: '/admin/locations/currencies',
    path: '/admin/locations/currencies',
    getParentRoute: () => PanelRoute,
  } as any)
const PanelAdminLocationsCountriesRoute =
  PanelAdminLocationsCountriesRouteImport.update({
    id: '/admin/locations/countries',
    path: '/admin/locations/countries',
    getParentRoute: () => PanelRoute,
  } as any)
const PanelAdminLocationsCitiesRoute =
  PanelAdminLocationsCitiesRouteImport.update({
    id: '/admin/locations/cities',
    path: '/admin/locations/cities',
    getParentRoute: () => PanelRoute,
  } as any)
const PanelHelpFaqIdEditRoute = PanelHelpFaqIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => PanelHelpFaqRoute,
} as any)
const PanelAdminRolesIdEditRoute = PanelAdminRolesIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => PanelAdminRolesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/404': typeof R404Route
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/register': typeof RegisterRouteWithChildren
  '/$': typeof PanelSplatRoute
  '/account': typeof PanelAccountRouteWithChildren
  '/assets': typeof PanelAssetsRoute
  '/categories': typeof PanelCategoriesRoute
  '/chat': typeof PanelChatRouteWithChildren
  '/collections': typeof PanelCollectionsRouteWithChildren
  '/coupons': typeof PanelCouponsRouteWithChildren
  '/couriers': typeof PanelCouriersRouteWithChildren
  '/customers': typeof PanelCustomersRouteWithChildren
  '/dashboard': typeof PanelDashboardRoute
  '/invoices': typeof PanelInvoicesRouteWithChildren
  '/notifications': typeof PanelNotificationsRoute
  '/orders': typeof PanelOrdersRouteWithChildren
  '/payment-methods': typeof PanelPaymentMethodsRouteWithChildren
  '/products': typeof PanelProductsRouteWithChildren
  '/properties': typeof PanelPropertiesRoute
  '/property-values': typeof PanelPropertyValuesRoute
  '/returns': typeof PanelReturnsRouteWithChildren
  '/stores': typeof PanelStoresRouteWithChildren
  '/subscribers': typeof PanelSubscribersRoute
  '/support': typeof PanelSupportRouteWithChildren
  '/tags': typeof PanelTagsRoute
  '/users': typeof PanelUsersRouteWithChildren
  '/wallet': typeof PanelWalletRoute
  '/register/status': typeof RegisterStatusRoute
  '/register/verify-phone': typeof RegisterVerifyPhoneRoute
  '/reset-password/$key': typeof ResetPasswordKeyRoute
  '/account/change-password': typeof PanelAccountChangePasswordRoute
  '/account/devices': typeof PanelAccountDevicesRoute
  '/account/notifications-prefs': typeof PanelAccountNotificationsPrefsRoute
  '/account/preferences': typeof PanelAccountPreferencesRoute
  '/account/sessions': typeof PanelAccountSessionsRoute
  '/admin/audit-log': typeof PanelAdminAuditLogRoute
  '/admin/feedback': typeof PanelAdminFeedbackRoute
  '/admin/options': typeof PanelAdminOptionsRoute
  '/admin/permission-resources': typeof PanelAdminPermissionResourcesRoute
  '/admin/permissions': typeof PanelAdminPermissionsRoute
  '/admin/role-policies': typeof PanelAdminRolePoliciesRoute
  '/admin/roles': typeof PanelAdminRolesRouteWithChildren
  '/admin/search-history': typeof PanelAdminSearchHistoryRoute
  '/admin/user-policies': typeof PanelAdminUserPoliciesRoute
  '/admin/visitors': typeof PanelAdminVisitorsRoute
  '/chat/$userId': typeof PanelChatUserIdRoute
  '/collections/new': typeof PanelCollectionsNewRoute
  '/communications/channels': typeof PanelCommunicationsChannelsRoute
  '/communications/templates': typeof PanelCommunicationsTemplatesRoute
  '/coupons/new': typeof PanelCouponsNewRoute
  '/customers/$id': typeof PanelCustomersIdRoute
  '/help/articles': typeof PanelHelpArticlesRoute
  '/help/faq': typeof PanelHelpFaqRouteWithChildren
  '/help/privacy': typeof PanelHelpPrivacyRoute
  '/help/terms': typeof PanelHelpTermsRoute
  '/invoices/$id': typeof PanelInvoicesIdRoute
  '/orders/$id': typeof PanelOrdersIdRoute
  '/payment-methods/new': typeof PanelPaymentMethodsNewRoute
  '/products/new': typeof PanelProductsNewRoute
  '/returns/$id': typeof PanelReturnsIdRoute
  '/reviews/product': typeof PanelReviewsProductRoute
  '/reviews/store': typeof PanelReviewsStoreRoute
  '/stores/$id': typeof PanelStoresIdRoute
  '/support/$sessionId': typeof PanelSupportSessionIdRoute
  '/users/$id': typeof PanelUsersIdRoute
  '/users/new': typeof PanelUsersNewRoute
  '/admin/locations/cities': typeof PanelAdminLocationsCitiesRoute
  '/admin/locations/countries': typeof PanelAdminLocationsCountriesRoute
  '/admin/locations/currencies': typeof PanelAdminLocationsCurrenciesRoute
  '/admin/locations/languages': typeof PanelAdminLocationsLanguagesRoute
  '/admin/locations/regions': typeof PanelAdminLocationsRegionsRoute
  '/collections/$id/edit': typeof PanelCollectionsIdEditRoute
  '/coupons/$id/edit': typeof PanelCouponsIdEditRoute
  '/coupons/$id/redemptions': typeof PanelCouponsIdRedemptionsRoute
  '/couriers/$id/edit': typeof PanelCouriersIdEditRoute
  '/help/faq/new': typeof PanelHelpFaqNewRoute
  '/payment-methods/$id/edit': typeof PanelPaymentMethodsIdEditRoute
  '/products/$id/edit': typeof PanelProductsIdEditRoute
  '/products/$id/reviews': typeof PanelProductsIdReviewsRoute
  '/admin/roles/$id/edit': typeof PanelAdminRolesIdEditRoute
  '/help/faq/$id/edit': typeof PanelHelpFaqIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/404': typeof R404Route
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/register': typeof RegisterRouteWithChildren
  '/$': typeof PanelSplatRoute
  '/account': typeof PanelAccountRouteWithChildren
  '/assets': typeof PanelAssetsRoute
  '/categories': typeof PanelCategoriesRoute
  '/chat': typeof PanelChatRouteWithChildren
  '/collections': typeof PanelCollectionsRouteWithChildren
  '/coupons': typeof PanelCouponsRouteWithChildren
  '/couriers': typeof PanelCouriersRouteWithChildren
  '/customers': typeof PanelCustomersRouteWithChildren
  '/dashboard': typeof PanelDashboardRoute
  '/invoices': typeof PanelInvoicesRouteWithChildren
  '/notifications': typeof PanelNotificationsRoute
  '/orders': typeof PanelOrdersRouteWithChildren
  '/payment-methods': typeof PanelPaymentMethodsRouteWithChildren
  '/products': typeof PanelProductsRouteWithChildren
  '/properties': typeof PanelPropertiesRoute
  '/property-values': typeof PanelPropertyValuesRoute
  '/returns': typeof PanelReturnsRouteWithChildren
  '/stores': typeof PanelStoresRouteWithChildren
  '/subscribers': typeof PanelSubscribersRoute
  '/support': typeof PanelSupportRouteWithChildren
  '/tags': typeof PanelTagsRoute
  '/users': typeof PanelUsersRouteWithChildren
  '/wallet': typeof PanelWalletRoute
  '/register/status': typeof RegisterStatusRoute
  '/register/verify-phone': typeof RegisterVerifyPhoneRoute
  '/reset-password/$key': typeof ResetPasswordKeyRoute
  '/account/change-password': typeof PanelAccountChangePasswordRoute
  '/account/devices': typeof PanelAccountDevicesRoute
  '/account/notifications-prefs': typeof PanelAccountNotificationsPrefsRoute
  '/account/preferences': typeof PanelAccountPreferencesRoute
  '/account/sessions': typeof PanelAccountSessionsRoute
  '/admin/audit-log': typeof PanelAdminAuditLogRoute
  '/admin/feedback': typeof PanelAdminFeedbackRoute
  '/admin/options': typeof PanelAdminOptionsRoute
  '/admin/permission-resources': typeof PanelAdminPermissionResourcesRoute
  '/admin/permissions': typeof PanelAdminPermissionsRoute
  '/admin/role-policies': typeof PanelAdminRolePoliciesRoute
  '/admin/roles': typeof PanelAdminRolesRouteWithChildren
  '/admin/search-history': typeof PanelAdminSearchHistoryRoute
  '/admin/user-policies': typeof PanelAdminUserPoliciesRoute
  '/admin/visitors': typeof PanelAdminVisitorsRoute
  '/chat/$userId': typeof PanelChatUserIdRoute
  '/collections/new': typeof PanelCollectionsNewRoute
  '/communications/channels': typeof PanelCommunicationsChannelsRoute
  '/communications/templates': typeof PanelCommunicationsTemplatesRoute
  '/coupons/new': typeof PanelCouponsNewRoute
  '/customers/$id': typeof PanelCustomersIdRoute
  '/help/articles': typeof PanelHelpArticlesRoute
  '/help/faq': typeof PanelHelpFaqRouteWithChildren
  '/help/privacy': typeof PanelHelpPrivacyRoute
  '/help/terms': typeof PanelHelpTermsRoute
  '/invoices/$id': typeof PanelInvoicesIdRoute
  '/orders/$id': typeof PanelOrdersIdRoute
  '/payment-methods/new': typeof PanelPaymentMethodsNewRoute
  '/products/new': typeof PanelProductsNewRoute
  '/returns/$id': typeof PanelReturnsIdRoute
  '/reviews/product': typeof PanelReviewsProductRoute
  '/reviews/store': typeof PanelReviewsStoreRoute
  '/stores/$id': typeof PanelStoresIdRoute
  '/support/$sessionId': typeof PanelSupportSessionIdRoute
  '/users/$id': typeof PanelUsersIdRoute
  '/users/new': typeof PanelUsersNewRoute
  '/admin/locations/cities': typeof PanelAdminLocationsCitiesRoute
  '/admin/locations/countries': typeof PanelAdminLocationsCountriesRoute
  '/admin/locations/currencies': typeof PanelAdminLocationsCurrenciesRoute
  '/admin/locations/languages': typeof PanelAdminLocationsLanguagesRoute
  '/admin/locations/regions': typeof PanelAdminLocationsRegionsRoute
  '/collections/$id/edit': typeof PanelCollectionsIdEditRoute
  '/coupons/$id/edit': typeof PanelCouponsIdEditRoute
  '/coupons/$id/redemptions': typeof PanelCouponsIdRedemptionsRoute
  '/couriers/$id/edit': typeof PanelCouriersIdEditRoute
  '/help/faq/new': typeof PanelHelpFaqNewRoute
  '/payment-methods/$id/edit': typeof PanelPaymentMethodsIdEditRoute
  '/products/$id/edit': typeof PanelProductsIdEditRoute
  '/products/$id/reviews': typeof PanelProductsIdReviewsRoute
  '/admin/roles/$id/edit': typeof PanelAdminRolesIdEditRoute
  '/help/faq/$id/edit': typeof PanelHelpFaqIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/404': typeof R404Route
  '/_panel': typeof PanelRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/register': typeof RegisterRouteWithChildren
  '/_panel/$': typeof PanelSplatRoute
  '/_panel/account': typeof PanelAccountRouteWithChildren
  '/_panel/assets': typeof PanelAssetsRoute
  '/_panel/categories': typeof PanelCategoriesRoute
  '/_panel/chat': typeof PanelChatRouteWithChildren
  '/_panel/collections': typeof PanelCollectionsRouteWithChildren
  '/_panel/coupons': typeof PanelCouponsRouteWithChildren
  '/_panel/couriers': typeof PanelCouriersRouteWithChildren
  '/_panel/customers': typeof PanelCustomersRouteWithChildren
  '/_panel/dashboard': typeof PanelDashboardRoute
  '/_panel/invoices': typeof PanelInvoicesRouteWithChildren
  '/_panel/notifications': typeof PanelNotificationsRoute
  '/_panel/orders': typeof PanelOrdersRouteWithChildren
  '/_panel/payment-methods': typeof PanelPaymentMethodsRouteWithChildren
  '/_panel/products': typeof PanelProductsRouteWithChildren
  '/_panel/properties': typeof PanelPropertiesRoute
  '/_panel/property-values': typeof PanelPropertyValuesRoute
  '/_panel/returns': typeof PanelReturnsRouteWithChildren
  '/_panel/stores': typeof PanelStoresRouteWithChildren
  '/_panel/subscribers': typeof PanelSubscribersRoute
  '/_panel/support': typeof PanelSupportRouteWithChildren
  '/_panel/tags': typeof PanelTagsRoute
  '/_panel/users': typeof PanelUsersRouteWithChildren
  '/_panel/wallet': typeof PanelWalletRoute
  '/register/status': typeof RegisterStatusRoute
  '/register/verify-phone': typeof RegisterVerifyPhoneRoute
  '/reset-password/$key': typeof ResetPasswordKeyRoute
  '/_panel/account/change-password': typeof PanelAccountChangePasswordRoute
  '/_panel/account/devices': typeof PanelAccountDevicesRoute
  '/_panel/account/notifications-prefs': typeof PanelAccountNotificationsPrefsRoute
  '/_panel/account/preferences': typeof PanelAccountPreferencesRoute
  '/_panel/account/sessions': typeof PanelAccountSessionsRoute
  '/_panel/admin/audit-log': typeof PanelAdminAuditLogRoute
  '/_panel/admin/feedback': typeof PanelAdminFeedbackRoute
  '/_panel/admin/options': typeof PanelAdminOptionsRoute
  '/_panel/admin/permission-resources': typeof PanelAdminPermissionResourcesRoute
  '/_panel/admin/permissions': typeof PanelAdminPermissionsRoute
  '/_panel/admin/role-policies': typeof PanelAdminRolePoliciesRoute
  '/_panel/admin/roles': typeof PanelAdminRolesRouteWithChildren
  '/_panel/admin/search-history': typeof PanelAdminSearchHistoryRoute
  '/_panel/admin/user-policies': typeof PanelAdminUserPoliciesRoute
  '/_panel/admin/visitors': typeof PanelAdminVisitorsRoute
  '/_panel/chat/$userId': typeof PanelChatUserIdRoute
  '/_panel/collections/new': typeof PanelCollectionsNewRoute
  '/_panel/communications/channels': typeof PanelCommunicationsChannelsRoute
  '/_panel/communications/templates': typeof PanelCommunicationsTemplatesRoute
  '/_panel/coupons/new': typeof PanelCouponsNewRoute
  '/_panel/customers/$id': typeof PanelCustomersIdRoute
  '/_panel/help/articles': typeof PanelHelpArticlesRoute
  '/_panel/help/faq': typeof PanelHelpFaqRouteWithChildren
  '/_panel/help/privacy': typeof PanelHelpPrivacyRoute
  '/_panel/help/terms': typeof PanelHelpTermsRoute
  '/_panel/invoices/$id': typeof PanelInvoicesIdRoute
  '/_panel/orders/$id': typeof PanelOrdersIdRoute
  '/_panel/payment-methods/new': typeof PanelPaymentMethodsNewRoute
  '/_panel/products/new': typeof PanelProductsNewRoute
  '/_panel/returns/$id': typeof PanelReturnsIdRoute
  '/_panel/reviews/product': typeof PanelReviewsProductRoute
  '/_panel/reviews/store': typeof PanelReviewsStoreRoute
  '/_panel/stores/$id': typeof PanelStoresIdRoute
  '/_panel/support/$sessionId': typeof PanelSupportSessionIdRoute
  '/_panel/users/$id': typeof PanelUsersIdRoute
  '/_panel/users/new': typeof PanelUsersNewRoute
  '/_panel/admin/locations/cities': typeof PanelAdminLocationsCitiesRoute
  '/_panel/admin/locations/countries': typeof PanelAdminLocationsCountriesRoute
  '/_panel/admin/locations/currencies': typeof PanelAdminLocationsCurrenciesRoute
  '/_panel/admin/locations/languages': typeof PanelAdminLocationsLanguagesRoute
  '/_panel/admin/locations/regions': typeof PanelAdminLocationsRegionsRoute
  '/_panel/collections/$id/edit': typeof PanelCollectionsIdEditRoute
  '/_panel/coupons/$id/edit': typeof PanelCouponsIdEditRoute
  '/_panel/coupons/$id/redemptions': typeof PanelCouponsIdRedemptionsRoute
  '/_panel/couriers/$id/edit': typeof PanelCouriersIdEditRoute
  '/_panel/help/faq/new': typeof PanelHelpFaqNewRoute
  '/_panel/payment-methods/$id/edit': typeof PanelPaymentMethodsIdEditRoute
  '/_panel/products/$id/edit': typeof PanelProductsIdEditRoute
  '/_panel/products/$id/reviews': typeof PanelProductsIdReviewsRoute
  '/_panel/admin/roles/$id/edit': typeof PanelAdminRolesIdEditRoute
  '/_panel/help/faq/$id/edit': typeof PanelHelpFaqIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/403'
    | '/404'
    | '/forgot-password'
    | '/login'
    | '/maintenance'
    | '/register'
    | '/$'
    | '/account'
    | '/assets'
    | '/categories'
    | '/chat'
    | '/collections'
    | '/coupons'
    | '/couriers'
    | '/customers'
    | '/dashboard'
    | '/invoices'
    | '/notifications'
    | '/orders'
    | '/payment-methods'
    | '/products'
    | '/properties'
    | '/property-values'
    | '/returns'
    | '/stores'
    | '/subscribers'
    | '/support'
    | '/tags'
    | '/users'
    | '/wallet'
    | '/register/status'
    | '/register/verify-phone'
    | '/reset-password/$key'
    | '/account/change-password'
    | '/account/devices'
    | '/account/notifications-prefs'
    | '/account/preferences'
    | '/account/sessions'
    | '/admin/audit-log'
    | '/admin/feedback'
    | '/admin/options'
    | '/admin/permission-resources'
    | '/admin/permissions'
    | '/admin/role-policies'
    | '/admin/roles'
    | '/admin/search-history'
    | '/admin/user-policies'
    | '/admin/visitors'
    | '/chat/$userId'
    | '/collections/new'
    | '/communications/channels'
    | '/communications/templates'
    | '/coupons/new'
    | '/customers/$id'
    | '/help/articles'
    | '/help/faq'
    | '/help/privacy'
    | '/help/terms'
    | '/invoices/$id'
    | '/orders/$id'
    | '/payment-methods/new'
    | '/products/new'
    | '/returns/$id'
    | '/reviews/product'
    | '/reviews/store'
    | '/stores/$id'
    | '/support/$sessionId'
    | '/users/$id'
    | '/users/new'
    | '/admin/locations/cities'
    | '/admin/locations/countries'
    | '/admin/locations/currencies'
    | '/admin/locations/languages'
    | '/admin/locations/regions'
    | '/collections/$id/edit'
    | '/coupons/$id/edit'
    | '/coupons/$id/redemptions'
    | '/couriers/$id/edit'
    | '/help/faq/new'
    | '/payment-methods/$id/edit'
    | '/products/$id/edit'
    | '/products/$id/reviews'
    | '/admin/roles/$id/edit'
    | '/help/faq/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/403'
    | '/404'
    | '/forgot-password'
    | '/login'
    | '/maintenance'
    | '/register'
    | '/$'
    | '/account'
    | '/assets'
    | '/categories'
    | '/chat'
    | '/collections'
    | '/coupons'
    | '/couriers'
    | '/customers'
    | '/dashboard'
    | '/invoices'
    | '/notifications'
    | '/orders'
    | '/payment-methods'
    | '/products'
    | '/properties'
    | '/property-values'
    | '/returns'
    | '/stores'
    | '/subscribers'
    | '/support'
    | '/tags'
    | '/users'
    | '/wallet'
    | '/register/status'
    | '/register/verify-phone'
    | '/reset-password/$key'
    | '/account/change-password'
    | '/account/devices'
    | '/account/notifications-prefs'
    | '/account/preferences'
    | '/account/sessions'
    | '/admin/audit-log'
    | '/admin/feedback'
    | '/admin/options'
    | '/admin/permission-resources'
    | '/admin/permissions'
    | '/admin/role-policies'
    | '/admin/roles'
    | '/admin/search-history'
    | '/admin/user-policies'
    | '/admin/visitors'
    | '/chat/$userId'
    | '/collections/new'
    | '/communications/channels'
    | '/communications/templates'
    | '/coupons/new'
    | '/customers/$id'
    | '/help/articles'
    | '/help/faq'
    | '/help/privacy'
    | '/help/terms'
    | '/invoices/$id'
    | '/orders/$id'
    | '/payment-methods/new'
    | '/products/new'
    | '/returns/$id'
    | '/reviews/product'
    | '/reviews/store'
    | '/stores/$id'
    | '/support/$sessionId'
    | '/users/$id'
    | '/users/new'
    | '/admin/locations/cities'
    | '/admin/locations/countries'
    | '/admin/locations/currencies'
    | '/admin/locations/languages'
    | '/admin/locations/regions'
    | '/collections/$id/edit'
    | '/coupons/$id/edit'
    | '/coupons/$id/redemptions'
    | '/couriers/$id/edit'
    | '/help/faq/new'
    | '/payment-methods/$id/edit'
    | '/products/$id/edit'
    | '/products/$id/reviews'
    | '/admin/roles/$id/edit'
    | '/help/faq/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/403'
    | '/404'
    | '/_panel'
    | '/forgot-password'
    | '/login'
    | '/maintenance'
    | '/register'
    | '/_panel/$'
    | '/_panel/account'
    | '/_panel/assets'
    | '/_panel/categories'
    | '/_panel/chat'
    | '/_panel/collections'
    | '/_panel/coupons'
    | '/_panel/couriers'
    | '/_panel/customers'
    | '/_panel/dashboard'
    | '/_panel/invoices'
    | '/_panel/notifications'
    | '/_panel/orders'
    | '/_panel/payment-methods'
    | '/_panel/products'
    | '/_panel/properties'
    | '/_panel/property-values'
    | '/_panel/returns'
    | '/_panel/stores'
    | '/_panel/subscribers'
    | '/_panel/support'
    | '/_panel/tags'
    | '/_panel/users'
    | '/_panel/wallet'
    | '/register/status'
    | '/register/verify-phone'
    | '/reset-password/$key'
    | '/_panel/account/change-password'
    | '/_panel/account/devices'
    | '/_panel/account/notifications-prefs'
    | '/_panel/account/preferences'
    | '/_panel/account/sessions'
    | '/_panel/admin/audit-log'
    | '/_panel/admin/feedback'
    | '/_panel/admin/options'
    | '/_panel/admin/permission-resources'
    | '/_panel/admin/permissions'
    | '/_panel/admin/role-policies'
    | '/_panel/admin/roles'
    | '/_panel/admin/search-history'
    | '/_panel/admin/user-policies'
    | '/_panel/admin/visitors'
    | '/_panel/chat/$userId'
    | '/_panel/collections/new'
    | '/_panel/communications/channels'
    | '/_panel/communications/templates'
    | '/_panel/coupons/new'
    | '/_panel/customers/$id'
    | '/_panel/help/articles'
    | '/_panel/help/faq'
    | '/_panel/help/privacy'
    | '/_panel/help/terms'
    | '/_panel/invoices/$id'
    | '/_panel/orders/$id'
    | '/_panel/payment-methods/new'
    | '/_panel/products/new'
    | '/_panel/returns/$id'
    | '/_panel/reviews/product'
    | '/_panel/reviews/store'
    | '/_panel/stores/$id'
    | '/_panel/support/$sessionId'
    | '/_panel/users/$id'
    | '/_panel/users/new'
    | '/_panel/admin/locations/cities'
    | '/_panel/admin/locations/countries'
    | '/_panel/admin/locations/currencies'
    | '/_panel/admin/locations/languages'
    | '/_panel/admin/locations/regions'
    | '/_panel/collections/$id/edit'
    | '/_panel/coupons/$id/edit'
    | '/_panel/coupons/$id/redemptions'
    | '/_panel/couriers/$id/edit'
    | '/_panel/help/faq/new'
    | '/_panel/payment-methods/$id/edit'
    | '/_panel/products/$id/edit'
    | '/_panel/products/$id/reviews'
    | '/_panel/admin/roles/$id/edit'
    | '/_panel/help/faq/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R403Route: typeof R403Route
  R404Route: typeof R404Route
  PanelRoute: typeof PanelRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MaintenanceRoute: typeof MaintenanceRoute
  RegisterRoute: typeof RegisterRouteWithChildren
  ResetPasswordKeyRoute: typeof ResetPasswordKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_panel': {
      id: '/_panel'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password/$key': {
      id: '/reset-password/$key'
      path: '/reset-password/$key'
      fullPath: '/reset-password/$key'
      preLoaderRoute: typeof ResetPasswordKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/verify-phone': {
      id: '/register/verify-phone'
      path: '/verify-phone'
      fullPath: '/register/verify-phone'
      preLoaderRoute: typeof RegisterVerifyPhoneRouteImport
      parentRoute: typeof RegisterRoute
    }
    '/register/status': {
      id: '/register/status'
      path: '/status'
      fullPath: '/register/status'
      preLoaderRoute: typeof RegisterStatusRouteImport
      parentRoute: typeof RegisterRoute
    }
    '/_panel/wallet': {
      id: '/_panel/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof PanelWalletRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/users': {
      id: '/_panel/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof PanelUsersRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/tags': {
      id: '/_panel/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof PanelTagsRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/support': {
      id: '/_panel/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof PanelSupportRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/subscribers': {
      id: '/_panel/subscribers'
      path: '/subscribers'
      fullPath: '/subscribers'
      preLoaderRoute: typeof PanelSubscribersRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/stores': {
      id: '/_panel/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof PanelStoresRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/returns': {
      id: '/_panel/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof PanelReturnsRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/property-values': {
      id: '/_panel/property-values'
      path: '/property-values'
      fullPath: '/property-values'
      preLoaderRoute: typeof PanelPropertyValuesRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/properties': {
      id: '/_panel/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PanelPropertiesRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/products': {
      id: '/_panel/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof PanelProductsRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/payment-methods': {
      id: '/_panel/payment-methods'
      path: '/payment-methods'
      fullPath: '/payment-methods'
      preLoaderRoute: typeof PanelPaymentMethodsRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/orders': {
      id: '/_panel/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof PanelOrdersRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/notifications': {
      id: '/_panel/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof PanelNotificationsRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/invoices': {
      id: '/_panel/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof PanelInvoicesRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/dashboard': {
      id: '/_panel/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PanelDashboardRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/customers': {
      id: '/_panel/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof PanelCustomersRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/couriers': {
      id: '/_panel/couriers'
      path: '/couriers'
      fullPath: '/couriers'
      preLoaderRoute: typeof PanelCouriersRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/coupons': {
      id: '/_panel/coupons'
      path: '/coupons'
      fullPath: '/coupons'
      preLoaderRoute: typeof PanelCouponsRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/collections': {
      id: '/_panel/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof PanelCollectionsRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/chat': {
      id: '/_panel/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof PanelChatRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/categories': {
      id: '/_panel/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof PanelCategoriesRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/assets': {
      id: '/_panel/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof PanelAssetsRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/account': {
      id: '/_panel/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof PanelAccountRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/$': {
      id: '/_panel/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof PanelSplatRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/users/new': {
      id: '/_panel/users/new'
      path: '/new'
      fullPath: '/users/new'
      preLoaderRoute: typeof PanelUsersNewRouteImport
      parentRoute: typeof PanelUsersRoute
    }
    '/_panel/users/$id': {
      id: '/_panel/users/$id'
      path: '/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof PanelUsersIdRouteImport
      parentRoute: typeof PanelUsersRoute
    }
    '/_panel/support/$sessionId': {
      id: '/_panel/support/$sessionId'
      path: '/$sessionId'
      fullPath: '/support/$sessionId'
      preLoaderRoute: typeof PanelSupportSessionIdRouteImport
      parentRoute: typeof PanelSupportRoute
    }
    '/_panel/stores/$id': {
      id: '/_panel/stores/$id'
      path: '/$id'
      fullPath: '/stores/$id'
      preLoaderRoute: typeof PanelStoresIdRouteImport
      parentRoute: typeof PanelStoresRoute
    }
    '/_panel/reviews/store': {
      id: '/_panel/reviews/store'
      path: '/reviews/store'
      fullPath: '/reviews/store'
      preLoaderRoute: typeof PanelReviewsStoreRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/reviews/product': {
      id: '/_panel/reviews/product'
      path: '/reviews/product'
      fullPath: '/reviews/product'
      preLoaderRoute: typeof PanelReviewsProductRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/returns/$id': {
      id: '/_panel/returns/$id'
      path: '/$id'
      fullPath: '/returns/$id'
      preLoaderRoute: typeof PanelReturnsIdRouteImport
      parentRoute: typeof PanelReturnsRoute
    }
    '/_panel/products/new': {
      id: '/_panel/products/new'
      path: '/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof PanelProductsNewRouteImport
      parentRoute: typeof PanelProductsRoute
    }
    '/_panel/payment-methods/new': {
      id: '/_panel/payment-methods/new'
      path: '/new'
      fullPath: '/payment-methods/new'
      preLoaderRoute: typeof PanelPaymentMethodsNewRouteImport
      parentRoute: typeof PanelPaymentMethodsRoute
    }
    '/_panel/orders/$id': {
      id: '/_panel/orders/$id'
      path: '/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof PanelOrdersIdRouteImport
      parentRoute: typeof PanelOrdersRoute
    }
    '/_panel/invoices/$id': {
      id: '/_panel/invoices/$id'
      path: '/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof PanelInvoicesIdRouteImport
      parentRoute: typeof PanelInvoicesRoute
    }
    '/_panel/help/terms': {
      id: '/_panel/help/terms'
      path: '/help/terms'
      fullPath: '/help/terms'
      preLoaderRoute: typeof PanelHelpTermsRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/help/privacy': {
      id: '/_panel/help/privacy'
      path: '/help/privacy'
      fullPath: '/help/privacy'
      preLoaderRoute: typeof PanelHelpPrivacyRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/help/faq': {
      id: '/_panel/help/faq'
      path: '/help/faq'
      fullPath: '/help/faq'
      preLoaderRoute: typeof PanelHelpFaqRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/help/articles': {
      id: '/_panel/help/articles'
      path: '/help/articles'
      fullPath: '/help/articles'
      preLoaderRoute: typeof PanelHelpArticlesRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/customers/$id': {
      id: '/_panel/customers/$id'
      path: '/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof PanelCustomersIdRouteImport
      parentRoute: typeof PanelCustomersRoute
    }
    '/_panel/coupons/new': {
      id: '/_panel/coupons/new'
      path: '/new'
      fullPath: '/coupons/new'
      preLoaderRoute: typeof PanelCouponsNewRouteImport
      parentRoute: typeof PanelCouponsRoute
    }
    '/_panel/communications/templates': {
      id: '/_panel/communications/templates'
      path: '/communications/templates'
      fullPath: '/communications/templates'
      preLoaderRoute: typeof PanelCommunicationsTemplatesRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/communications/channels': {
      id: '/_panel/communications/channels'
      path: '/communications/channels'
      fullPath: '/communications/channels'
      preLoaderRoute: typeof PanelCommunicationsChannelsRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/collections/new': {
      id: '/_panel/collections/new'
      path: '/new'
      fullPath: '/collections/new'
      preLoaderRoute: typeof PanelCollectionsNewRouteImport
      parentRoute: typeof PanelCollectionsRoute
    }
    '/_panel/chat/$userId': {
      id: '/_panel/chat/$userId'
      path: '/$userId'
      fullPath: '/chat/$userId'
      preLoaderRoute: typeof PanelChatUserIdRouteImport
      parentRoute: typeof PanelChatRoute
    }
    '/_panel/admin/visitors': {
      id: '/_panel/admin/visitors'
      path: '/admin/visitors'
      fullPath: '/admin/visitors'
      preLoaderRoute: typeof PanelAdminVisitorsRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/admin/user-policies': {
      id: '/_panel/admin/user-policies'
      path: '/admin/user-policies'
      fullPath: '/admin/user-policies'
      preLoaderRoute: typeof PanelAdminUserPoliciesRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/admin/search-history': {
      id: '/_panel/admin/search-history'
      path: '/admin/search-history'
      fullPath: '/admin/search-history'
      preLoaderRoute: typeof PanelAdminSearchHistoryRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/admin/roles': {
      id: '/_panel/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof PanelAdminRolesRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/admin/role-policies': {
      id: '/_panel/admin/role-policies'
      path: '/admin/role-policies'
      fullPath: '/admin/role-policies'
      preLoaderRoute: typeof PanelAdminRolePoliciesRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/admin/permissions': {
      id: '/_panel/admin/permissions'
      path: '/admin/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof PanelAdminPermissionsRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/admin/permission-resources': {
      id: '/_panel/admin/permission-resources'
      path: '/admin/permission-resources'
      fullPath: '/admin/permission-resources'
      preLoaderRoute: typeof PanelAdminPermissionResourcesRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/admin/options': {
      id: '/_panel/admin/options'
      path: '/admin/options'
      fullPath: '/admin/options'
      preLoaderRoute: typeof PanelAdminOptionsRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/admin/feedback': {
      id: '/_panel/admin/feedback'
      path: '/admin/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof PanelAdminFeedbackRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/admin/audit-log': {
      id: '/_panel/admin/audit-log'
      path: '/admin/audit-log'
      fullPath: '/admin/audit-log'
      preLoaderRoute: typeof PanelAdminAuditLogRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/account/sessions': {
      id: '/_panel/account/sessions'
      path: '/sessions'
      fullPath: '/account/sessions'
      preLoaderRoute: typeof PanelAccountSessionsRouteImport
      parentRoute: typeof PanelAccountRoute
    }
    '/_panel/account/preferences': {
      id: '/_panel/account/preferences'
      path: '/preferences'
      fullPath: '/account/preferences'
      preLoaderRoute: typeof PanelAccountPreferencesRouteImport
      parentRoute: typeof PanelAccountRoute
    }
    '/_panel/account/notifications-prefs': {
      id: '/_panel/account/notifications-prefs'
      path: '/notifications-prefs'
      fullPath: '/account/notifications-prefs'
      preLoaderRoute: typeof PanelAccountNotificationsPrefsRouteImport
      parentRoute: typeof PanelAccountRoute
    }
    '/_panel/account/devices': {
      id: '/_panel/account/devices'
      path: '/devices'
      fullPath: '/account/devices'
      preLoaderRoute: typeof PanelAccountDevicesRouteImport
      parentRoute: typeof PanelAccountRoute
    }
    '/_panel/account/change-password': {
      id: '/_panel/account/change-password'
      path: '/change-password'
      fullPath: '/account/change-password'
      preLoaderRoute: typeof PanelAccountChangePasswordRouteImport
      parentRoute: typeof PanelAccountRoute
    }
    '/_panel/products/$id/reviews': {
      id: '/_panel/products/$id/reviews'
      path: '/$id/reviews'
      fullPath: '/products/$id/reviews'
      preLoaderRoute: typeof PanelProductsIdReviewsRouteImport
      parentRoute: typeof PanelProductsRoute
    }
    '/_panel/products/$id/edit': {
      id: '/_panel/products/$id/edit'
      path: '/$id/edit'
      fullPath: '/products/$id/edit'
      preLoaderRoute: typeof PanelProductsIdEditRouteImport
      parentRoute: typeof PanelProductsRoute
    }
    '/_panel/payment-methods/$id/edit': {
      id: '/_panel/payment-methods/$id/edit'
      path: '/$id/edit'
      fullPath: '/payment-methods/$id/edit'
      preLoaderRoute: typeof PanelPaymentMethodsIdEditRouteImport
      parentRoute: typeof PanelPaymentMethodsRoute
    }
    '/_panel/help/faq/new': {
      id: '/_panel/help/faq/new'
      path: '/new'
      fullPath: '/help/faq/new'
      preLoaderRoute: typeof PanelHelpFaqNewRouteImport
      parentRoute: typeof PanelHelpFaqRoute
    }
    '/_panel/couriers/$id/edit': {
      id: '/_panel/couriers/$id/edit'
      path: '/$id/edit'
      fullPath: '/couriers/$id/edit'
      preLoaderRoute: typeof PanelCouriersIdEditRouteImport
      parentRoute: typeof PanelCouriersRoute
    }
    '/_panel/coupons/$id/redemptions': {
      id: '/_panel/coupons/$id/redemptions'
      path: '/$id/redemptions'
      fullPath: '/coupons/$id/redemptions'
      preLoaderRoute: typeof PanelCouponsIdRedemptionsRouteImport
      parentRoute: typeof PanelCouponsRoute
    }
    '/_panel/coupons/$id/edit': {
      id: '/_panel/coupons/$id/edit'
      path: '/$id/edit'
      fullPath: '/coupons/$id/edit'
      preLoaderRoute: typeof PanelCouponsIdEditRouteImport
      parentRoute: typeof PanelCouponsRoute
    }
    '/_panel/collections/$id/edit': {
      id: '/_panel/collections/$id/edit'
      path: '/$id/edit'
      fullPath: '/collections/$id/edit'
      preLoaderRoute: typeof PanelCollectionsIdEditRouteImport
      parentRoute: typeof PanelCollectionsRoute
    }
    '/_panel/admin/locations/regions': {
      id: '/_panel/admin/locations/regions'
      path: '/admin/locations/regions'
      fullPath: '/admin/locations/regions'
      preLoaderRoute: typeof PanelAdminLocationsRegionsRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/admin/locations/languages': {
      id: '/_panel/admin/locations/languages'
      path: '/admin/locations/languages'
      fullPath: '/admin/locations/languages'
      preLoaderRoute: typeof PanelAdminLocationsLanguagesRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/admin/locations/currencies': {
      id: '/_panel/admin/locations/currencies'
      path: '/admin/locations/currencies'
      fullPath: '/admin/locations/currencies'
      preLoaderRoute: typeof PanelAdminLocationsCurrenciesRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/admin/locations/countries': {
      id: '/_panel/admin/locations/countries'
      path: '/admin/locations/countries'
      fullPath: '/admin/locations/countries'
      preLoaderRoute: typeof PanelAdminLocationsCountriesRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/admin/locations/cities': {
      id: '/_panel/admin/locations/cities'
      path: '/admin/locations/cities'
      fullPath: '/admin/locations/cities'
      preLoaderRoute: typeof PanelAdminLocationsCitiesRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/help/faq/$id/edit': {
      id: '/_panel/help/faq/$id/edit'
      path: '/$id/edit'
      fullPath: '/help/faq/$id/edit'
      preLoaderRoute: typeof PanelHelpFaqIdEditRouteImport
      parentRoute: typeof PanelHelpFaqRoute
    }
    '/_panel/admin/roles/$id/edit': {
      id: '/_panel/admin/roles/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/roles/$id/edit'
      preLoaderRoute: typeof PanelAdminRolesIdEditRouteImport
      parentRoute: typeof PanelAdminRolesRoute
    }
  }
}

interface PanelAccountRouteChildren {
  PanelAccountChangePasswordRoute: typeof PanelAccountChangePasswordRoute
  PanelAccountDevicesRoute: typeof PanelAccountDevicesRoute
  PanelAccountNotificationsPrefsRoute: typeof PanelAccountNotificationsPrefsRoute
  PanelAccountPreferencesRoute: typeof PanelAccountPreferencesRoute
  PanelAccountSessionsRoute: typeof PanelAccountSessionsRoute
}

const PanelAccountRouteChildren: PanelAccountRouteChildren = {
  PanelAccountChangePasswordRoute: PanelAccountChangePasswordRoute,
  PanelAccountDevicesRoute: PanelAccountDevicesRoute,
  PanelAccountNotificationsPrefsRoute: PanelAccountNotificationsPrefsRoute,
  PanelAccountPreferencesRoute: PanelAccountPreferencesRoute,
  PanelAccountSessionsRoute: PanelAccountSessionsRoute,
}

const PanelAccountRouteWithChildren = PanelAccountRoute._addFileChildren(
  PanelAccountRouteChildren,
)

interface PanelChatRouteChildren {
  PanelChatUserIdRoute: typeof PanelChatUserIdRoute
}

const PanelChatRouteChildren: PanelChatRouteChildren = {
  PanelChatUserIdRoute: PanelChatUserIdRoute,
}

const PanelChatRouteWithChildren = PanelChatRoute._addFileChildren(
  PanelChatRouteChildren,
)

interface PanelCollectionsRouteChildren {
  PanelCollectionsNewRoute: typeof PanelCollectionsNewRoute
  PanelCollectionsIdEditRoute: typeof PanelCollectionsIdEditRoute
}

const PanelCollectionsRouteChildren: PanelCollectionsRouteChildren = {
  PanelCollectionsNewRoute: PanelCollectionsNewRoute,
  PanelCollectionsIdEditRoute: PanelCollectionsIdEditRoute,
}

const PanelCollectionsRouteWithChildren =
  PanelCollectionsRoute._addFileChildren(PanelCollectionsRouteChildren)

interface PanelCouponsRouteChildren {
  PanelCouponsNewRoute: typeof PanelCouponsNewRoute
  PanelCouponsIdEditRoute: typeof PanelCouponsIdEditRoute
  PanelCouponsIdRedemptionsRoute: typeof PanelCouponsIdRedemptionsRoute
}

const PanelCouponsRouteChildren: PanelCouponsRouteChildren = {
  PanelCouponsNewRoute: PanelCouponsNewRoute,
  PanelCouponsIdEditRoute: PanelCouponsIdEditRoute,
  PanelCouponsIdRedemptionsRoute: PanelCouponsIdRedemptionsRoute,
}

const PanelCouponsRouteWithChildren = PanelCouponsRoute._addFileChildren(
  PanelCouponsRouteChildren,
)

interface PanelCouriersRouteChildren {
  PanelCouriersIdEditRoute: typeof PanelCouriersIdEditRoute
}

const PanelCouriersRouteChildren: PanelCouriersRouteChildren = {
  PanelCouriersIdEditRoute: PanelCouriersIdEditRoute,
}

const PanelCouriersRouteWithChildren = PanelCouriersRoute._addFileChildren(
  PanelCouriersRouteChildren,
)

interface PanelCustomersRouteChildren {
  PanelCustomersIdRoute: typeof PanelCustomersIdRoute
}

const PanelCustomersRouteChildren: PanelCustomersRouteChildren = {
  PanelCustomersIdRoute: PanelCustomersIdRoute,
}

const PanelCustomersRouteWithChildren = PanelCustomersRoute._addFileChildren(
  PanelCustomersRouteChildren,
)

interface PanelInvoicesRouteChildren {
  PanelInvoicesIdRoute: typeof PanelInvoicesIdRoute
}

const PanelInvoicesRouteChildren: PanelInvoicesRouteChildren = {
  PanelInvoicesIdRoute: PanelInvoicesIdRoute,
}

const PanelInvoicesRouteWithChildren = PanelInvoicesRoute._addFileChildren(
  PanelInvoicesRouteChildren,
)

interface PanelOrdersRouteChildren {
  PanelOrdersIdRoute: typeof PanelOrdersIdRoute
}

const PanelOrdersRouteChildren: PanelOrdersRouteChildren = {
  PanelOrdersIdRoute: PanelOrdersIdRoute,
}

const PanelOrdersRouteWithChildren = PanelOrdersRoute._addFileChildren(
  PanelOrdersRouteChildren,
)

interface PanelPaymentMethodsRouteChildren {
  PanelPaymentMethodsNewRoute: typeof PanelPaymentMethodsNewRoute
  PanelPaymentMethodsIdEditRoute: typeof PanelPaymentMethodsIdEditRoute
}

const PanelPaymentMethodsRouteChildren: PanelPaymentMethodsRouteChildren = {
  PanelPaymentMethodsNewRoute: PanelPaymentMethodsNewRoute,
  PanelPaymentMethodsIdEditRoute: PanelPaymentMethodsIdEditRoute,
}

const PanelPaymentMethodsRouteWithChildren =
  PanelPaymentMethodsRoute._addFileChildren(PanelPaymentMethodsRouteChildren)

interface PanelProductsRouteChildren {
  PanelProductsNewRoute: typeof PanelProductsNewRoute
  PanelProductsIdEditRoute: typeof PanelProductsIdEditRoute
  PanelProductsIdReviewsRoute: typeof PanelProductsIdReviewsRoute
}

const PanelProductsRouteChildren: PanelProductsRouteChildren = {
  PanelProductsNewRoute: PanelProductsNewRoute,
  PanelProductsIdEditRoute: PanelProductsIdEditRoute,
  PanelProductsIdReviewsRoute: PanelProductsIdReviewsRoute,
}

const PanelProductsRouteWithChildren = PanelProductsRoute._addFileChildren(
  PanelProductsRouteChildren,
)

interface PanelReturnsRouteChildren {
  PanelReturnsIdRoute: typeof PanelReturnsIdRoute
}

const PanelReturnsRouteChildren: PanelReturnsRouteChildren = {
  PanelReturnsIdRoute: PanelReturnsIdRoute,
}

const PanelReturnsRouteWithChildren = PanelReturnsRoute._addFileChildren(
  PanelReturnsRouteChildren,
)

interface PanelStoresRouteChildren {
  PanelStoresIdRoute: typeof PanelStoresIdRoute
}

const PanelStoresRouteChildren: PanelStoresRouteChildren = {
  PanelStoresIdRoute: PanelStoresIdRoute,
}

const PanelStoresRouteWithChildren = PanelStoresRoute._addFileChildren(
  PanelStoresRouteChildren,
)

interface PanelSupportRouteChildren {
  PanelSupportSessionIdRoute: typeof PanelSupportSessionIdRoute
}

const PanelSupportRouteChildren: PanelSupportRouteChildren = {
  PanelSupportSessionIdRoute: PanelSupportSessionIdRoute,
}

const PanelSupportRouteWithChildren = PanelSupportRoute._addFileChildren(
  PanelSupportRouteChildren,
)

interface PanelUsersRouteChildren {
  PanelUsersIdRoute: typeof PanelUsersIdRoute
  PanelUsersNewRoute: typeof PanelUsersNewRoute
}

const PanelUsersRouteChildren: PanelUsersRouteChildren = {
  PanelUsersIdRoute: PanelUsersIdRoute,
  PanelUsersNewRoute: PanelUsersNewRoute,
}

const PanelUsersRouteWithChildren = PanelUsersRoute._addFileChildren(
  PanelUsersRouteChildren,
)

interface PanelAdminRolesRouteChildren {
  PanelAdminRolesIdEditRoute: typeof PanelAdminRolesIdEditRoute
}

const PanelAdminRolesRouteChildren: PanelAdminRolesRouteChildren = {
  PanelAdminRolesIdEditRoute: PanelAdminRolesIdEditRoute,
}

const PanelAdminRolesRouteWithChildren = PanelAdminRolesRoute._addFileChildren(
  PanelAdminRolesRouteChildren,
)

interface PanelHelpFaqRouteChildren {
  PanelHelpFaqNewRoute: typeof PanelHelpFaqNewRoute
  PanelHelpFaqIdEditRoute: typeof PanelHelpFaqIdEditRoute
}

const PanelHelpFaqRouteChildren: PanelHelpFaqRouteChildren = {
  PanelHelpFaqNewRoute: PanelHelpFaqNewRoute,
  PanelHelpFaqIdEditRoute: PanelHelpFaqIdEditRoute,
}

const PanelHelpFaqRouteWithChildren = PanelHelpFaqRoute._addFileChildren(
  PanelHelpFaqRouteChildren,
)

interface PanelRouteChildren {
  PanelSplatRoute: typeof PanelSplatRoute
  PanelAccountRoute: typeof PanelAccountRouteWithChildren
  PanelAssetsRoute: typeof PanelAssetsRoute
  PanelCategoriesRoute: typeof PanelCategoriesRoute
  PanelChatRoute: typeof PanelChatRouteWithChildren
  PanelCollectionsRoute: typeof PanelCollectionsRouteWithChildren
  PanelCouponsRoute: typeof PanelCouponsRouteWithChildren
  PanelCouriersRoute: typeof PanelCouriersRouteWithChildren
  PanelCustomersRoute: typeof PanelCustomersRouteWithChildren
  PanelDashboardRoute: typeof PanelDashboardRoute
  PanelInvoicesRoute: typeof PanelInvoicesRouteWithChildren
  PanelNotificationsRoute: typeof PanelNotificationsRoute
  PanelOrdersRoute: typeof PanelOrdersRouteWithChildren
  PanelPaymentMethodsRoute: typeof PanelPaymentMethodsRouteWithChildren
  PanelProductsRoute: typeof PanelProductsRouteWithChildren
  PanelPropertiesRoute: typeof PanelPropertiesRoute
  PanelPropertyValuesRoute: typeof PanelPropertyValuesRoute
  PanelReturnsRoute: typeof PanelReturnsRouteWithChildren
  PanelStoresRoute: typeof PanelStoresRouteWithChildren
  PanelSubscribersRoute: typeof PanelSubscribersRoute
  PanelSupportRoute: typeof PanelSupportRouteWithChildren
  PanelTagsRoute: typeof PanelTagsRoute
  PanelUsersRoute: typeof PanelUsersRouteWithChildren
  PanelWalletRoute: typeof PanelWalletRoute
  PanelAdminAuditLogRoute: typeof PanelAdminAuditLogRoute
  PanelAdminFeedbackRoute: typeof PanelAdminFeedbackRoute
  PanelAdminOptionsRoute: typeof PanelAdminOptionsRoute
  PanelAdminPermissionResourcesRoute: typeof PanelAdminPermissionResourcesRoute
  PanelAdminPermissionsRoute: typeof PanelAdminPermissionsRoute
  PanelAdminRolePoliciesRoute: typeof PanelAdminRolePoliciesRoute
  PanelAdminRolesRoute: typeof PanelAdminRolesRouteWithChildren
  PanelAdminSearchHistoryRoute: typeof PanelAdminSearchHistoryRoute
  PanelAdminUserPoliciesRoute: typeof PanelAdminUserPoliciesRoute
  PanelAdminVisitorsRoute: typeof PanelAdminVisitorsRoute
  PanelCommunicationsChannelsRoute: typeof PanelCommunicationsChannelsRoute
  PanelCommunicationsTemplatesRoute: typeof PanelCommunicationsTemplatesRoute
  PanelHelpArticlesRoute: typeof PanelHelpArticlesRoute
  PanelHelpFaqRoute: typeof PanelHelpFaqRouteWithChildren
  PanelHelpPrivacyRoute: typeof PanelHelpPrivacyRoute
  PanelHelpTermsRoute: typeof PanelHelpTermsRoute
  PanelReviewsProductRoute: typeof PanelReviewsProductRoute
  PanelReviewsStoreRoute: typeof PanelReviewsStoreRoute
  PanelAdminLocationsCitiesRoute: typeof PanelAdminLocationsCitiesRoute
  PanelAdminLocationsCountriesRoute: typeof PanelAdminLocationsCountriesRoute
  PanelAdminLocationsCurrenciesRoute: typeof PanelAdminLocationsCurrenciesRoute
  PanelAdminLocationsLanguagesRoute: typeof PanelAdminLocationsLanguagesRoute
  PanelAdminLocationsRegionsRoute: typeof PanelAdminLocationsRegionsRoute
}

const PanelRouteChildren: PanelRouteChildren = {
  PanelSplatRoute: PanelSplatRoute,
  PanelAccountRoute: PanelAccountRouteWithChildren,
  PanelAssetsRoute: PanelAssetsRoute,
  PanelCategoriesRoute: PanelCategoriesRoute,
  PanelChatRoute: PanelChatRouteWithChildren,
  PanelCollectionsRoute: PanelCollectionsRouteWithChildren,
  PanelCouponsRoute: PanelCouponsRouteWithChildren,
  PanelCouriersRoute: PanelCouriersRouteWithChildren,
  PanelCustomersRoute: PanelCustomersRouteWithChildren,
  PanelDashboardRoute: PanelDashboardRoute,
  PanelInvoicesRoute: PanelInvoicesRouteWithChildren,
  PanelNotificationsRoute: PanelNotificationsRoute,
  PanelOrdersRoute: PanelOrdersRouteWithChildren,
  PanelPaymentMethodsRoute: PanelPaymentMethodsRouteWithChildren,
  PanelProductsRoute: PanelProductsRouteWithChildren,
  PanelPropertiesRoute: PanelPropertiesRoute,
  PanelPropertyValuesRoute: PanelPropertyValuesRoute,
  PanelReturnsRoute: PanelReturnsRouteWithChildren,
  PanelStoresRoute: PanelStoresRouteWithChildren,
  PanelSubscribersRoute: PanelSubscribersRoute,
  PanelSupportRoute: PanelSupportRouteWithChildren,
  PanelTagsRoute: PanelTagsRoute,
  PanelUsersRoute: PanelUsersRouteWithChildren,
  PanelWalletRoute: PanelWalletRoute,
  PanelAdminAuditLogRoute: PanelAdminAuditLogRoute,
  PanelAdminFeedbackRoute: PanelAdminFeedbackRoute,
  PanelAdminOptionsRoute: PanelAdminOptionsRoute,
  PanelAdminPermissionResourcesRoute: PanelAdminPermissionResourcesRoute,
  PanelAdminPermissionsRoute: PanelAdminPermissionsRoute,
  PanelAdminRolePoliciesRoute: PanelAdminRolePoliciesRoute,
  PanelAdminRolesRoute: PanelAdminRolesRouteWithChildren,
  PanelAdminSearchHistoryRoute: PanelAdminSearchHistoryRoute,
  PanelAdminUserPoliciesRoute: PanelAdminUserPoliciesRoute,
  PanelAdminVisitorsRoute: PanelAdminVisitorsRoute,
  PanelCommunicationsChannelsRoute: PanelCommunicationsChannelsRoute,
  PanelCommunicationsTemplatesRoute: PanelCommunicationsTemplatesRoute,
  PanelHelpArticlesRoute: PanelHelpArticlesRoute,
  PanelHelpFaqRoute: PanelHelpFaqRouteWithChildren,
  PanelHelpPrivacyRoute: PanelHelpPrivacyRoute,
  PanelHelpTermsRoute: PanelHelpTermsRoute,
  PanelReviewsProductRoute: PanelReviewsProductRoute,
  PanelReviewsStoreRoute: PanelReviewsStoreRoute,
  PanelAdminLocationsCitiesRoute: PanelAdminLocationsCitiesRoute,
  PanelAdminLocationsCountriesRoute: PanelAdminLocationsCountriesRoute,
  PanelAdminLocationsCurrenciesRoute: PanelAdminLocationsCurrenciesRoute,
  PanelAdminLocationsLanguagesRoute: PanelAdminLocationsLanguagesRoute,
  PanelAdminLocationsRegionsRoute: PanelAdminLocationsRegionsRoute,
}

const PanelRouteWithChildren = PanelRoute._addFileChildren(PanelRouteChildren)

interface RegisterRouteChildren {
  RegisterStatusRoute: typeof RegisterStatusRoute
  RegisterVerifyPhoneRoute: typeof RegisterVerifyPhoneRoute
}

const RegisterRouteChildren: RegisterRouteChildren = {
  RegisterStatusRoute: RegisterStatusRoute,
  RegisterVerifyPhoneRoute: RegisterVerifyPhoneRoute,
}

const RegisterRouteWithChildren = RegisterRoute._addFileChildren(
  RegisterRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R403Route: R403Route,
  R404Route: R404Route,
  PanelRoute: PanelRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MaintenanceRoute: MaintenanceRoute,
  RegisterRoute: RegisterRouteWithChildren,
  ResetPasswordKeyRoute: ResetPasswordKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
